
language: cpp
compiler: gcc
os: linux

before_install:
  - sudo apt-get -y install liblua5.2-dev

install:
  - git clone --branch=master https://github.com/izuzanak/cont.git ~/build/izuzanak/cont

  - cd ~/build/izuzanak/cont/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/izuzanak/yapgen/build
  - cmake ../yapgen
  - make

